# docker-compose.auth.yml
# NOT FOR PRODUCTION ##################################
# Must be merged with the base compose.               #
# - Adds authentication to FROST.                     #
# #####################################################

services:
  frost:
    environment:
      - auth_provider=de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthProvider
      - auth_db_driver=org.postgresql.Driver
      - auth_db_url=jdbc:postgresql://database:5432/sensorthings
      - auth_allowAnonymousRead=${FROST_ALLOW_ANONYMOUS_READ:-true}
      - auth_autoUpdateDatabase=true

  database:
    environment:
      - auth_requireReadAuth=${FROST_REQUIRE_READ_AUTH:-true}
      - auth_requireWriteAuth=${FROST_REQUIRE_WRITE_AUTH:-true}
    secrets:
      - frost_credentials 
    volumes:
      - ./init-db.sh:/init-db.sh
    entrypoint: ["/init-db.sh"] 

secrets:
  frost_credentials:
    file: ${FROST_CREDENTIALS_PATH:-./secrets/credentials/frost_credentials.json}

